/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mases_datadistributionmanager_NativeInterface */

#ifndef _Included_org_mases_datadistributionmanager_NativeInterface
#define _Included_org_mases_datadistributionmanager_NativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    DataDistribution_create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_mases_datadistributionmanager_NativeInterface_DataDistribution_1create
  (JNIEnv *, jclass);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    DataDistributionCallback_create
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_org_mases_datadistributionmanager_NativeInterface_DataDistributionCallback_1create
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    DataDistributionCallback_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_mases_datadistributionmanager_NativeInterface_DataDistributionCallback_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    DataDistributionChannelCallback_create
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_org_mases_datadistributionmanager_NativeInterface_DataDistributionChannelCallback_1create
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    DataDistributionChannelCallback_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_mases_datadistributionmanager_NativeInterface_DataDistributionChannelCallback_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    DataDistributionMastershipCallback_create
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_org_mases_datadistributionmanager_NativeInterface_DataDistributionMastershipCallback_1create
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    DataDistributionMastershipCallback_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_mases_datadistributionmanager_NativeInterface_DataDistributionMastershipCallback_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistribution_Initialize
 * Signature: (JJLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistribution_1Initialize
  (JNIEnv *, jclass, jlong, jlong, jstring, jstring, jstring);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistribution_Initialize2
 * Signature: (JJ[Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistribution_1Initialize2
  (JNIEnv *, jclass, jlong, jlong, jobjectArray, jstring, jstring);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistribution_RequestMastershipManager
 * Signature: (JJLjava/lang/String;[Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistribution_1RequestMastershipManager
  (JNIEnv *, jclass, jlong, jlong, jstring, jobjectArray);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistribution_GetSubsystemManager
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistribution_1GetSubsystemManager
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistribution_GetMastershipManager
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistribution_1GetMastershipManager
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistribution_GetProtocol
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistribution_1GetProtocol
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistribution_GetProtocolLib
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistribution_1GetProtocolLib
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistribution_GetMastershipLib
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistribution_1GetMastershipLib
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionSubsystem_GetServerLostTimeout
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionSubsystem_1GetServerLostTimeout
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionSubsystem_GetMaxMessageSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionSubsystem_1GetMaxMessageSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionSubsystem_Start
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionSubsystem_1Start
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionSubsystem_Stop
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionSubsystem_1Stop
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionSubsystem_CreateChannel
 * Signature: (JLjava/lang/String;JI[Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionSubsystem_1CreateChannel
  (JNIEnv *, jclass, jlong, jstring, jlong, jint, jobjectArray);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionSubsystem_StartChannel
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionSubsystem_1StartChannel
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionSubsystem_StopChannel
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionSubsystem_1StopChannel
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionSubsystem_SetParameter
 * Signature: (JJLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionSubsystem_1SetParameter__JJLjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jlong, jlong, jstring, jstring);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionSubsystem_SetParameter
 * Signature: (JJILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionSubsystem_1SetParameter__JJILjava_lang_String_2
  (JNIEnv *, jclass, jlong, jlong, jint, jstring);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionSubsystem_GetParameter
 * Signature: (JJLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionSubsystem_1GetParameter__JJLjava_lang_String_2
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionSubsystem_GetParameter
 * Signature: (JJI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionSubsystem_1GetParameter__JJI
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionSubsystem_Lock
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionSubsystem_1Lock
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionSubsystem_Unlock
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionSubsystem_1Unlock
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionSubsystem_SeekChannel
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionSubsystem_1SeekChannel
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionSubsystem_DeleteChannel
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionSubsystem_1DeleteChannel
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionSubsystem_WriteOnChannel
 * Signature: (JJLjava/lang/String;[BZJ)J
 */
JNIEXPORT jlong JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionSubsystem_1WriteOnChannel
  (JNIEnv *, jclass, jlong, jlong, jstring, jbyteArray, jboolean, jlong);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionSubsystem_ReadFromChannel
 * Signature: (JJJJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionSubsystem_1ReadFromChannel
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionSubsystem_ChangeDirectionOnChannel
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionSubsystem_1ChangeDirectionOnChannel
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionMastershipCommon_Start
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionMastershipCommon_1Start
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionMastershipCommon_Stop
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionMastershipCommon_1Stop
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionMastershipCommon_GetIamNextPrimary
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionMastershipCommon_1GetIamNextPrimary
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionMastershipCommon_RequestIAmNextPrimary
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionMastershipCommon_1RequestIAmNextPrimary
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionMastershipCommon_GetClusterIndexes
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionMastershipCommon_1GetClusterIndexes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionMastershipCommon_GetStateOf
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionMastershipCommon_1GetStateOf
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionMastershipCommon_GetClusterHealth
 * Signature: (JJ)Lorg/mases/datadistributionmanager/ClusterHealthElement;
 */
JNIEXPORT jobject JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionMastershipCommon_1GetClusterHealth
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionMastershipCommon_GetMyState
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionMastershipCommon_1GetMyState
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionMastershipCommon_ChangeMyState
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionMastershipCommon_1ChangeMyState
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionMastershipCommon_ChangeState
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionMastershipCommon_1ChangeState
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionMastershipCommon_GetLocalServerId
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionMastershipCommon_1GetLocalServerId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionMastershipCommon_GetPrimaryServerId
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionMastershipCommon_1GetPrimaryServerId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionMastershipCommon_GetMessageDelay
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionMastershipCommon_1GetMessageDelay
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_mases_datadistributionmanager_NativeInterface
 * Method:    IDataDistributionMastershipCommon_GetUpTime
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_mases_datadistributionmanager_NativeInterface_IDataDistributionMastershipCommon_1GetUpTime
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
